#specify input_file filepath and name
input_file: ..\SampleFiles\SampleLogicFile.txt

#specify output_file output filepath and name
output_file: ..\SampleFiles\SampleLogicFile_Minimized.txt

#specify log_file log filepath and name
log_file: ..\SampleFiles\minimizer_log.txt

#optional: specify input_encoding encoding of the input file. defaults to utf-8.
input_encoding: utf-8

#optional: specify max_variables. defaults to None (no max). else ignores expressions with more variables
max_variables: 