#specify input_file filepath and name
input_file: ../SampleFiles/SampleLogicFile.txt

#specify output_file output filepath and name
output_file: ../SampleFiles/SampleLogicFile_Minimized.txt

#specify where to save counts of results filepath and name
counts_output_file: ../SampleFiles/SampleLogicFile_Counts.txt

#specify log_file log filepath and name
log_file: ../SampleFiles/minimizer_log.txt

#specify temp_file log filepath and name
temp_file: ../SampleFiles/temp_output.txt

#optional: specify input_encoding encoding of the input file. defaults to utf-8.
input_encoding: utf-8

#optional: specify max time in seconds to spend on each big statement. default is no limit.
timeout: 20